초기세팅
wecode-bootcamp-korea/39-2nd-bZrunch-backend pull request #1
Opened 2022-11-28 08:49 UTC by MatheGoD

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 2차 프로젝트 초기 세팅

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 2차 프로젝트 초기 세팅 (Layered Pattern 적용) 

<br />

## :: 테스트 결과 이미지

<br />

## :: 기타 질문 및 특이 사항

2022-11-28 10:46 UTC, bigfanoftim requested changes
PR 타이틀과 커밋 메세지 신경써서 다시 작성해 주세요.

답이 있는 것은 아닙니다만 보통 다른 사람들과 프로젝트를 진행함에 있어 중요한 부분입니다. 최소한 통일된 하나의 양식으로 작성하는 습관을 들여주세요.

`PR 타이틀` Add: 초기 세팅
`커밋 메세지` Add: 초기 세팅

2022-11-28 10:46 UTC, bigfanoftim commented on app.js
> +// const { routes } = require("./src/routes");
```suggestion
```
불필요한 주석 전부 지워주세요.

2022-11-28 10:46 UTC, bigfanoftim commented on app.js
> +});
`pull_request_template.md`에 따라 테스트 결과 스크린샷 첨부해주세요.

2022-11-28 11:07 UTC, MatheGoD commented on app.js
> +});
네 알겠습니다!

2022-11-29 01:57 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-29 01:58 UTC, merged