[FEATURE] 카카오 결제
wecode-bootcamp-korea/39-2nd-bZrunch-backend pull request #12
Opened 2022-12-07 08:41 UTC by MatheGoD

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 카카오 외부 API를 이용해 카카오페이(단건 결제) 구현
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 처음에는 결제 사전 준비 단계부터 백에서 하려고 했지만 axios 에러가 자주 발생하여, FRONT와 동시에 작업 중 
FRONT에서 먼저 완료하여 카카오 서버로 제품 상세 내용 및 결제 금액을 보내고 그에 대한 승인코드를 받아 저장

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![image](https://user-images.githubusercontent.com/110371295/206129773-cd12ed36-8b8d-4ea6-8d76-1f6420059b4f.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
프론트와 통신 완료 후 올릴 예정(현재 DB가 초기화 되어 진행 중단)

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-07 08:57 UTC, bigfanoftim requested changes

2022-12-07 08:57 UTC, bigfanoftim commented on src/services/paymentService.js
> +            partner_user_id: 'partner_user_id',
이 부분은 원래 string으로 보내는건가요?

2022-12-07 09:54 UTC, MatheGoD commented on src/services/paymentService.js
> +            partner_user_id: 'partner_user_id',
두 부분 가맹점 주문번호와 가맹점 회원 아이디로 스트링으로 전달됩니다.

2022-12-08 04:37 UTC, bigfanoftim requested changes
LGTM 👍 
Conflict 해결해주세요~

2022-12-08 04:37 UTC, bigfanoftim commented on src/services/paymentService.js
> +            partner_user_id: 'partner_user_id',
우선 해당 부분에 대한 모델링이 진행되지 않았기 때문에 랜덤 스트링값으로 하드코딩했다고 생각하면 될까요??ㅎㅎ

2022-12-08 04:48 UTC, MatheGoD commented on src/services/paymentService.js
> +            partner_user_id: 'partner_user_id',
네~ 해당 부분은 본래 따로 관리를 해야 되는 부분으로 알고 있으나 주문번호의 경우 결제 기능 구현이 우선이기도 하고 중복으로 요청이 여러 번 되어도 결제가 성공 되는 것으로 봐서는 하드코딩으로 진행해도 괜찮다고 생각했습니다.

2022-12-08 05:00 UTC, bigfanoftim approved these changes
LGTM 👍

2022-12-08 05:00 UTC, merged