[ADD] 글 좋아요 구현 및 UNIT TEST 진행
wecode-bootcamp-korea/39-2nd-bZrunch-backend pull request #4
Opened 2022-11-30 11:33 UTC by MatheGoD

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 좋아하기 API 구현
- UNIT TEST 진행

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 작성된 글 '좋아요' 및 '좋아요'된 글 누를 시 '좋아요' 취소 구현
- 만들어진 API에 대한 UNIT TEST 진행

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![image](https://user-images.githubusercontent.com/110371295/204778635-134b85ee-a782-45b0-aa80-e60a2337f922.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
![image](https://user-images.githubusercontent.com/110371295/204785309-b3a15c4c-6e6a-4bf5-b913-97664d7660bf.png)
![image](https://user-images.githubusercontent.com/110371295/204785374-444fbdfb-6acd-4139-adb8-dc396c5e6df1.png)

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
![image](https://user-images.githubusercontent.com/110371295/204785493-53ccbd60-4126-45ac-bddd-71c1f8de7cf7.png)

<br />

## :: 기타 질문 및 특이 사항

2022-12-01 01:26 UTC, bigfanoftim requested changes
test code랑 postman 이미지에서도 그렇듯 req body에 id를 넘겨주는 목적이 무엇인가요?

2022-12-01 01:26 UTC, bigfanoftim commented on .env.test
> +DB_PASSWORD=@Mathe0713
👀

2022-12-01 02:23 UTC, MatheGoD commented on .env.test
> +DB_PASSWORD=@Mathe0713
> test code랑 postman 이미지에서도 그렇듯 req body에 id를 넘겨주는 목적이 무엇인가요?
사실 이 부분이 이번 PR 올릴 시 피드백을 받으려고 했던 부분인데, 본래 로직이라면 소셜 로그인이 구현된 후 토큰 값이 티키타카 하면서 req.user에 담겨 user_id = req.user로 받아지는 것이 정상이지만 아직 구현 전인 것도 있고 unit test도 우선 진행해보고 싶어 바디 값으로 선 진행 하였습니다. 추후 req.user로 로직 변경 및 진행 예정입니다.

> .env.test 
.gitignore에 제대로 적용이 안되었군요 다시 정정해서 올리도록 하겠습니다.

2022-12-01 03:09 UTC, bigfanoftim commented on .env.test
> +DB_PASSWORD=@Mathe0713
그럼 해당 PR은 라벨 지워두고 아직 머지하지 않겠습니다. 선행 작업 완료된 이후에 다시 확인할게요!

2022-12-01 03:34 UTC, MatheGoD commented on .env.test
> +DB_PASSWORD=@Mathe0713
네! 알겠습니다~!!

2022-12-08 04:34 UTC, bigfanoftim approved these changes
👍

2022-12-08 04:34 UTC, merged