[FEATURE] 검색 기능 구현 및 유닛 테스트
wecode-bootcamp-korea/39-2nd-bZrunch-backend pull request #6
Opened 2022-12-01 14:10 UTC by MatheGoD

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 글 제목 검색 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- (프론트에서 latency 설정 후) 특정 단어를 검색 창에 입력했을 때, 그 단어가 포함된 글들의 제목을 불러 오는 로직 

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![image](https://user-images.githubusercontent.com/110371295/205073678-db8da8bc-3865-4afc-b347-fb22b19b623c.png)

2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
![image](https://user-images.githubusercontent.com/110371295/205073644-8d54987b-ff1d-4b60-87b2-c08d9edb4860.png)

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
![image](https://user-images.githubusercontent.com/110371295/205073742-7d657323-a8f1-48f2-972b-920593195cae.png)

4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항 
- 글로벌 에러 핸들링 에 대한 커버리지를 굳이 맞추지 않아도 된다고 들었는데 맞는 건가요?

2022-12-02 02:26 UTC, bigfanoftim requested changes

2022-12-02 02:26 UTC, bigfanoftim commented on src/controllers/writingsController.js
> +    } else return res.status(204).json({});
```suggestion
    if (!searchWord) {
        return res.status(204).end();
        // 혹은 기획에 따라 에러를 반환할 수도
    }   
     
    const result = await writingsService.searchTitle(searchWord);
    return res.status(200).json({ result });    
```
if else로 작성하여 서로에게 묶여있는 구조로 코드를 작성하는 것보다 다음과 같이 수정하면 더 좋을 것 같습니다.
이런식으로 예외처리가 필요한 경우 미리 해당 경우를 리턴해주는 패턴을 early return 패턴이라고 합니다.

2022-12-02 02:26 UTC, bigfanoftim commented on src/services/writingsService.js
> +    return result;
```suggestion
    return await writingsDao.searchTitle(searchWord);
```

2022-12-02 02:26 UTC, bigfanoftim commented on src/models/writingsDao.js
> +    };
escaping이 필요없는 value인데 굳이 작성하신 이유가 있을까요?

2022-12-02 02:26 UTC, bigfanoftim commented on tests/search.test.js
> +describe('Search', () => {
```suggestion
describe('Search Writings By Title', () => {
```

2022-12-02 06:17 UTC, bigfanoftim requested changes

2022-12-02 06:17 UTC, bigfanoftim commented on .prettierrc
> +}
👍

2022-12-02 06:17 UTC, bigfanoftim commented on package.json
> +    },
`test scripts`에 이미 관련 플래그가 추가되어 있는데 따로 추가하신 이유가 있을까요?

2022-12-02 06:17 UTC, bigfanoftim commented on tests/search.test.js
> +        // await appDataSource.query(`TRUNCATE TABLE writings`);
👀

2022-12-02 06:17 UTC, bigfanoftim commented on tests/search.test.js
> +    test('Writing Created', async () => {
생성을 위한 테스트가 아닌 검색을 위한 테스트이지 않을까요?

2022-12-02 06:59 UTC, MatheGoD commented on package.json
> +    },
초반 오타로 인해 스크립이 안 먹혀서 다른 방법을 찾다 저렇게 적용한 거였는데 오타를 찾고 나서는 필요가 없어졌지만 지우질 못했습니다. 바로 지우겠습니다.

2022-12-02 07:04 UTC, MatheGoD commented on tests/search.test.js
> +        // await appDataSource.query(`TRUNCATE TABLE writings`);
사실상 불필요한 부분이지만 추후 제 편의를 위해 남겨둔 코드였습니다. 지우겠습니다.

2022-12-02 07:17 UTC, MatheGoD commented on tests/search.test.js
> +    test('Writing Created', async () => {
앗..부주의에서 나온 실수 입니다! 바로 고치겠습니다.

2022-12-05 06:38 UTC, bigfanoftim requested changes

2022-12-05 06:38 UTC, bigfanoftim commented on .prettierrc
> +>>>>>>> f670458... [FEATURE] 검색 기능 구현 및 유닛 테스트
👀

2022-12-05 07:48 UTC, bigfanoftim requested changes
계속 남아있네요~ 푸시하셨으면 라벨 변경 전 Files changed를 확인해 주세요.

2022-12-05 07:48 UTC, bigfanoftim commented on app.js
>  const createApp = () => {
👀

2022-12-05 08:36 UTC, MatheGoD commented on app.js
>  const createApp = () => {
하..다 저장이 안 된 상태로 푸쉬되었네요..
죄송합니다.

2022-12-06 02:08 UTC, bigfanoftim approved these changes
👍

2022-12-06 02:09 UTC, merged